import Head from "next/head";

import Home from "@/components/views/home/Home";

const home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&family=Protest+Riot&family=Racing+Sans+One&display=swap" rel="stylesheet"/>
      </Head>

      <Home />
    </>
  );
};

export default home;
